# -*- coding: utf-8 -*-
"""English copy. Every visible string on the site lives here."""

EN = {
"meta": {
  "index":   {"title": "Milana PMU — Powder Brows, Lip Blush & Scar Camouflage in Dubai & Sharjah",
              "desc": "Russian permanent makeup artist working at your home in Dubai and Sharjah. Powder brows and lip blush from 499 AED, plus scar and stretch mark camouflage matched to your skin tone."},
  "services":{"title": "Services — Powder Brows, Lip Blush, Scar Camouflage | Milana PMU",
              "desc": "Powder brows and lip blush from 499 AED, and camouflage tattooing for scars, stretch marks, vitiligo and grafts. Home service in Dubai and Sharjah."},
  "pricing": {"title": "Pricing | Milana PMU Dubai & Sharjah",
              "desc": "Powder brows and lip blush 499 AED, home visit included. Camouflage quoted per area after a patch test."},
  "results": {"title": "Results — Before & After | Milana PMU Dubai",
              "desc": "Healed powder brows, lip blush and scar camouflage, photographed in daylight without filters."},
  "about":   {"title": "About Milana — Russian PMU Artist in the UAE",
              "desc": "Russian permanent makeup and camouflage artist working at clients' homes across Dubai and Sharjah. Sterile, single-use, pigment mixed per client."},
  "faq":     {"title": "FAQ — Pain, Healing, Aftercare, Camouflage | Milana PMU",
              "desc": "How much it hurts, how long it lasts, what the first month looks like, and which scars can and cannot be camouflaged."},
  "contact": {"title": "Contact & Booking | Milana PMU Dubai & Sharjah",
              "desc": "Book a permanent makeup or camouflage appointment in Dubai or Sharjah. WhatsApp is the fastest way to reach Milana."},
},

"ui": {
  "skip": "Skip to content", "language": "Language",
  "nav_primary": "Treatments and results", "nav_secondary": "About and contact",
  "book": "Book", "menu": "Menu", "call": "Call", "quick_contact": "Quick contact",
  "wa_text": "Hi Milana! I would like to book a PMU appointment.",
  "wa_aria": "Message Milana on WhatsApp",
  "more": "Read more", "before": "Before", "after": "After",
  "ba_aria": "Drag to compare before and after",
  "tone_aria": "Skin tone",
},

"nav": {"index": "Home", "services": "Services", "results": "Results", "pricing": "Pricing",
        "about": "About", "faq": "FAQ", "contact": "Contact"},

"footer": {
  "blurb": "Permanent makeup and camouflage tattooing at your home in Dubai and Sharjah. Every pigment is mixed to match your skin, not picked off a chart.",
  "sitemap": "Pages", "contact": "Contact",
  "areas": "Home service · Dubai & Sharjah",
  "hours": "By appointment",
  "rights": "All rights reserved.",
  "founder_label": "Founder:",
},

"home": {
  "hero_alt": "Placeholder for the hero photograph — a permanent makeup treatment in progress",
  "eyebrow": "Russian PMU artist · Dubai & Sharjah",
  "title_html": "Pigment matched<br>to <em>your skin</em>",
  "lead": "Powder brows, lip blush, lashline and scar camouflage — done at your home, with a pigment mixed for your undertone and tested on your skin before the first pass.",
  "cta_primary": "Book on WhatsApp",
  "cta_secondary": "See results",
  "facts": [
    ("home", "Home service across Dubai & Sharjah"),
    ("shield", "Sterile, single-use tooling, opened in front of you"),
    ("drop", "Pigment mixed per client, never off the shelf"),
  ],
  "services": {
    "eyebrow": "What I do",
    "h2": "Four treatments, one method",
    "lead": "Brows, lips and lashline are about proportion and colour. Camouflage is about making something stop catching the eye. All four start the same way — by reading your undertone in daylight.",
    "items": [
      {"img": "service-brows.webp", "alt": "Placeholder for a powder brows photograph",
       "title": "Powder brows", "anchor": "#powder-brows", "price": "499 AED", "price_note": "from",
       "text": "A soft gradient that reads as light powder — airy at the front, denser at the tail. Shape mapped to your face, not to a template."},
      {"img": "service-lips.webp", "alt": "Placeholder for a lip blush photograph",
       "title": "Lip blush", "anchor": "#lip-blush", "price": "499 AED", "price_note": "from",
       "text": "Colour worked into the lip to restore the border and even out tone. No lipstick edge — it reads as your lips on their best day."},
      {"img": "service-lashline.webp", "alt": "A close-up of a woman's eye area in daylight",
       "title": "Lashline", "anchor": "#lashline", "price": "299 AED", "price_note": "from",
       "text": "Pigment set between the lashes so the lash line reads fuller and the eye looks more open. No line on the lid — it stops where the lashes do."},
      {"img": "service-camo.webp", "alt": "Placeholder for a scar camouflage photograph",
       "title": "Scar & stretch mark camouflage", "anchor": "#camouflage",
       "price": "On request", "price_note": "per area",
       "text": "Pigment matched to the skin around a scar, stretch mark or graft, built across sessions until the contrast is gone."},
    ],
  },
  "camo": {
    "eyebrow": "The specialism",
    "h2": "Camouflage is colour science",
    "lead": "A scar is not simply white. It is a different colour to the skin beside it, in a different undertone, on tissue that holds pigment differently. Matching it takes a mix, a test on your skin, and patience across sessions — which is why most artists do not offer it.",
    "bullets": ["Stretch marks", "C-section and surgical scars", "Vitiligo and lost pigment",
                "Scalp camouflage", "Skin grafts and burn scars", "Tummy tuck and liposuction",
                "Old marks from injury", "Areas after mastectomy"],
    "matcher_title": "Find your starting point",
    "matcher_lead": "Pick the tone closest to the skin around your scar. The panel shows where a first session would start — a base plus a corrector, mixed deliberately lighter than the target, because pigment darkens as it heals.",
    "labels": {"skin": "Your skin", "base": "Base", "corr": "Corrector"},
    "disclaimer": "Illustrative. Every real match is mixed and tested on your skin at the consultation.",
    "cta": "About camouflage",
  },
  "results": {
    "eyebrow": "Results",
    "h2": "Healed work",
    "lead": "Brows, lips, and the two planned together. Photographed in daylight, without filters.",
    "items": [
      {"img": "gallery-brows-01.webp", "alt": "Healed powder brows, close-up", "tag": "Powder brows",
       "caption": "Soft powder finish, denser at the tail than at the front."},
      {"img": "gallery-lips-01.webp", "alt": "Healed lip blush in a deep berry tone", "tag": "Lip blush",
       "caption": "Deep berry, worked into the lip with no lipstick edge."},
      {"img": "gallery-face-01.webp", "alt": "Client with healed powder brows and lip blush", "tag": "Brows + lips",
       "caption": "Brows and lips in one plan, matched to the same undertone."},
    ],
    "cta": "See all results",
  },
  "healing": {
    "eyebrow": "What to expect",
    "h2": "The first month, day by day",
    "lead": "Colour looks strongest on day one and settles over four weeks. Knowing the sequence is what stops people panicking on day three.",
    "steps": [
      {"day": "Day 0", "title": "Freshly done",
       "text": "Colour sits 30–40% darker than the healed result. Slight swelling on lips is normal."},
      {"day": "Day 2–3", "title": "Darkest point",
       "text": "The pigment oxidises and looks bold. This is the stage clients worry about. It passes."},
      {"day": "Day 4–7", "title": "Flaking",
       "text": "A fine layer lifts away on its own. Do not pick it — it takes pigment with it."},
      {"day": "Day 8–14", "title": "The grey phase",
       "text": "New skin covers the pigment and the colour looks patchy and faded. It comes back."},
      {"day": "Day 28", "title": "Settled",
       "text": "True colour is visible. This is when we book the touch-up and correct anything uneven."},
    ],
    "note": "The touch-up sits four to eight weeks after the first session. It is part of the treatment, not an upsell: the first pass builds the base, the second sets the final colour.",
  },
  "home_service": {
    "eyebrow": "Home service",
    "h2": "I come to you",
    "lead": "Dubai and Sharjah. You need a table, a socket and about three hours. Everything else arrives in the case.",
    "img_alt": "Placeholder for a photograph of the home service setup",
    "steps": [
      {"title": "Message on WhatsApp",
       "text": "Send a daylight photo of the area and tell me what you want. You get an honest answer on what is realistic and how many sessions it takes."},
      {"title": "Consultation at your door",
       "text": "Medical history, patch test, and the shape or the colour match agreed before anything starts. Nothing is tattooed until you say yes in a mirror."},
      {"title": "The session",
       "text": "Two to three hours for brows or lips, one to three for a camouflage area. Sterile, single-use tooling, unsealed in front of you."},
      {"title": "Aftercare and touch-up",
       "text": "Written aftercare, a check-in during the healing week, and the touch-up booked at four to eight weeks."},
    ],
  },
  "founder": {
    "eyebrow": "The person at your door",
    "h2": "Meet Milana",
    "img_alt": "Placeholder for a portrait of Milana at work",
    "paras": [
      "I am a Russian permanent makeup artist working across Dubai and Sharjah. I chose to do a short list properly rather than twenty treatments adequately — brows, lips, lashline, and the camouflage work most artists turn away.",
      "Letting someone into your home is a bigger ask than walking into a studio. So the kit is unsealed in front of you, the pigment is mixed against your skin while you watch, and nothing is tattooed until you have seen the shape in a mirror and said yes to it.",
    ],
    "facts": [
      ("Speaks", "Russian & English"),
      ("Works on", "Brows · Lips · Camouflage"),
      ("Covers", "Dubai & Sharjah"),
    ],
    "cta": "How I work",
  },
  "reviews": {
    "eyebrow": "In their words",
    "h2": "Client reviews",
    "lead": "Collected after the touch-up, once the colour has settled and there is something real to say.",
    "slots": [
      {"text": "I had my C-section scar done over three sessions. Milana was straight with me from the first photo — she said what was realistic and how many visits it would take, and it went exactly like that. Somewhere around the second session I stopped looking for it in the mirror.",
       "who": "Dana · Scar camouflage · Dubai Marina"},
      {"text": "She came while the baby was asleep, set everything up on my dining table and was gone in three hours. My brows still look like mine, just there. I would have been happy after the first session — she was right to insist on the touch-up.",
       "who": "Yulia · Powder brows · Al Barsha"},
      {"text": "I was afraid of ending up with a lipstick line. She mixed the colour against my skin, showed me on my own lip and adjusted it twice before starting. It healed to exactly the shade she said it would.",
       "who": "Aisha · Lip blush · Jumeirah"},
    ],
    "ig_cta": "See the work on Instagram",
  },
  "faq": {
    "eyebrow": "Before you book",
    "h2": "Common questions",
    "cta": "All questions",
    "items": [
      {"q": "Does it hurt?", "a": [
        "Topical anaesthetic goes on before and during the session. Most clients describe brows as scratching and lips as a warm buzzing. Camouflage on the body is usually the easiest of the three.",
        "Skin is more sensitive in the week before a period — worth planning around."]},
      {"q": "How long does it last?", "a": [
        "Powder brows one to two years, lip blush one to three, depending on skin type, sun exposure and skincare. Camouflage fades slowly and is topped up when needed.",
        "Acids, retinol and strong sun shorten all of it."]},
      {"q": "How soon after surgery can a scar be camouflaged?", "a": [
        "Usually at least twelve months, and only once your surgeon or doctor confirms the scar is fully mature, closed and no longer changing. Working too early can affect how it settles."]},
    ],
  },
  "cta": {
    "eyebrow": "Booking",
    "h2": "Let's look at your case",
    "lead": "Send a photo on WhatsApp and you get an honest answer: what is possible, how many sessions it takes, and what it costs. No obligation.",
    "primary": "Message on WhatsApp",
    "secondary": "Contact details",
  },
},

"services": {
  "eyebrow": "Services",
  "h1": "Brows, lips, lashline, camouflage",
  "lead": "Four treatments. Each one starts with your undertone and ends with a touch-up that sets the final colour.",
  "good_for_label": "Good for",
  "see_pricing": "See pricing",
  "items": [
    {"id": "powder-brows", "eyebrow": "Brows", "title": "Powder brows",
     "lead": "A soft gradient that reads as light powder, not as a drawn line.",
     "paras": [
       "The shape is mapped on your face first, measured against your bone structure and your natural brow, then adjusted until you are happy with the outline drawn on. Nothing is pigmented until you have seen it in a mirror and said yes.",
       "Colour is mixed to sit just under your hair at the front and slightly deeper at the tail, so the brow has direction instead of reading as a block. It looks strongest for the first three days, then settles into the tone you approved."],
     "good_for": ["Sparse or over-plucked brows", "Brows that disappear without makeup",
                  "Asymmetry you correct by hand every morning", "Oily skin, where microblading strokes blur"],
     "specs": [("Session", "2.5-3 h"), ("Touch-up", "4-8 weeks"), ("Lasts", "1-2 years"), ("From", "499 AED")],
     "img": "service-brows.webp", "alt": "Placeholder for a powder brows photograph",
     "cta": "Book powder brows"},
    {"id": "lip-blush", "eyebrow": "Lips", "title": "Lip blush",
     "lead": "Colour worked into the lip itself — definition without a lipstick edge.",
     "paras": [
       "Lip blush corrects three things at once: an uneven natural tone, a border that has softened over the years, and a shape that is fuller on one side than the other. The pigment is translucent, so the result moves with your lips rather than sitting on top of them.",
       "Lips swell for about a day and go through a dry, flaky stage in the first week. The procedure can trigger cold sores — if you get them, arrange antiviral cover before the session and tell me at the consultation."],
     "good_for": ["Pale or uneven lip colour", "A border that has lost its definition",
                  "Slight asymmetry between the two sides", "Wanting colour without daily makeup"],
     "specs": [("Session", "2.5-3 h"), ("Touch-up", "6-8 weeks"), ("Lasts", "1-3 years"), ("From", "499 AED")],
     "img": "service-lips.webp", "alt": "Placeholder for a lip blush photograph",
     "cta": "Book lip blush"},
    {"id": "lashline", "eyebrow": "Eyes", "title": "Lashline",
     "lead": "Pigment set between the lashes — the eye looks more open, with nothing drawn on the lid.",
     "paras": [
       "The pigment goes into the gaps between your own lashes, so the line of growth reads denser and darker than it is. It stops where the lashes stop: there is no flick, no wing and no line sitting on the skin above them.",
       "It is the quietest of the four treatments and the one people notice without being able to say why. Because the area is small and the skin there is thin, the session is shorter than brows or lips, and the pigment settles within the first week."],
     "good_for": ["Sparse or pale lashes that disappear without mascara",
                  "Wanting definition that survives the gym and the pool",
                  "Eyes that read tired in photographs",
                  "Anyone who wants less than a full eyeliner"],
     "specs": [("Touch-up", "4-8 weeks"), ("Lasts", "1-2 years"), ("From", "299 AED")],
     "img": "service-lashline.webp", "alt": "A close-up of a woman's eye area in daylight",
     "cta": "Book lashline"},
    {"id": "camouflage", "eyebrow": "Camouflage", "title": "Scar & stretch mark camouflage",
     "lead": "Making a mark stop catching the eye — by matching it, not covering it.",
     "paras": [
       "Camouflage tattooing places skin-toned pigment into a mature scar, stretch mark or area of lost pigment so it blends with the skin around it. It does not remove the scar and it does not change its texture. What it removes is the colour contrast that makes your eye land there.",
       "The work runs across sessions, usually two to four, eight to twelve weeks apart. Scar tissue holds pigment unpredictably, so each session is planned from how the last one healed rather than from a fixed plan.",
       "Not every scar is suitable. Raised, keloid or still-red scars are not treated, and a patch test on a small area comes before any large one is started."],
     "good_for": ["White, mature stretch marks on hips, thighs or chest",
                  "C-section, tummy tuck and mastectomy scars",
                  "Vitiligo and other areas of lost pigment",
                  "Skin grafts and healed burn scars",
                  "Scalp camouflage over scars in the hairline",
                  "Old marks left by injury or surgery"],
     "specs": [("Session", "1-3 h"), ("Sessions", "2-4"), ("Spacing", "8-12 weeks"), ("Price", "On consultation")],
     "img": "service-camo.webp", "alt": "Placeholder for a scar camouflage photograph",
     "cta": "Ask about camouflage"},
  ],
  "cta": {"eyebrow": "Not sure which", "h2": "Send a photo and find out",
          "lead": "Describe what bothers you and attach a daylight photo. You get a straight answer on which treatment fits, or whether none of them does.",
          "primary": "Message on WhatsApp", "secondary": "Contact details"},
},

"pricing": {
  "eyebrow": "Pricing",
  "h1": "The menu",
  "lead": "Brows, lips and lashline have a fixed price. Camouflage is quoted per area after a consultation, because a four-centimetre scar and a full abdomen are not the same job.",
  "caption": "Prices in AED. The home visit in Dubai and Sharjah is included.",

  "menu": {
    "eyebrow": "Permanent makeup",
    "h2": "Enhance your beauty, naturally",
    "currency": "AED",
    "items": [
      {"name": "Powder brows", "tag": "Soft, natural and long-lasting brows",
       "price": "499", "anchor": "#powder-brows"},
      {"name": "Lip blush", "tag": "Natural tint and definition for beautiful lips",
       "price": "499", "anchor": "#lip-blush"},
      {"name": "Lashline", "tag": "Define your eyes with subtle perfection",
       "price": "299", "anchor": "#lashline"},
      {"name": "Powder brows + lip blush", "tag": "The perfect combo for a complete look",
       "price": "799", "anchor": "#powder-brows", "featured": True, "badge": "Save 199 AED"},
    ],
    "cta": "Book this",
  },
  "badges": ["Natural results", "Premium pigments", "Safe and hygienic", "Done by the artist herself"],

  "offer": {
    "label": "Model offer",
    "price": "349 AED",
    "terms": "Materials only",
    "flag": "Limited slots",
    "h3": "Come as a model",
    "text": "A small number of appointments each month are open at cost — you pay for the pigment, needles and single-use kit, nothing for the work. The treatment is the same one everyone else books. In return I photograph the healed result for my portfolio, and you approve every photo before it is used.",
    "cta": "Ask about model slots",
  },

  "table_h2": "Quoted after a consultation",
  "th_service": "Treatment", "th_time": "In the chair", "th_price": "Price",
  "rows": [
    {"name": "Touch-up", "note": "Booked 4-8 weeks after the first session", "duration": "1-2 h", "price": "On consultation"},
    {"name": "Scar & stretch mark camouflage", "note": "Quoted per area after a patch test", "duration": "1-3 h", "price": "On consultation"},
    {"name": "Scalp camouflage", "note": "Quoted after a consultation", "duration": "1-3 h", "price": "On consultation"},
    {"name": "Correction of previous PMU", "note": "Assessed from daylight photos first", "duration": "2-3 h", "price": "On consultation"},
  ],
  "notes": [
    "The home visit across Dubai and Sharjah is included — there is no call-out fee.",
    "A deposit confirms the date and comes off the final price.",
    "Camouflage always begins with a patch test, booked separately from the first full session.",
    "Correcting another artist's work is quoted only after I have seen daylight photos.",
  ],
  "included": {
    "eyebrow": "In the price",
    "h2": "What every appointment includes",
    "items": [
      ("shield", "Sterile setup", "Needles, cartridges, pigment cups and gloves are single-use and unsealed in front of you."),
      ("drop", "A pigment mixed for you", "Colour is mixed on the day against your skin, not chosen from a chart in advance."),
      ("home", "The visit itself", "Travel to your address in Dubai or Sharjah is included in the price."),
      ("clock", "Aftercare and follow-up", "Written aftercare, a check-in during healing, and my number for anything that worries you."),
    ],
  },
  "cta": {"eyebrow": "Booking", "h2": "Get a price for your case",
          "lead": "For camouflage, send a daylight photo and the age of the scar. You get a quote and a realistic number of sessions before you commit.",
          "primary": "Message on WhatsApp", "secondary": "Contact details"},
},

"results": {
  "eyebrow": "Results",
  "h1": "Healed work",
  "lead": "Photographed in daylight, without filters or retouching. Fresh work always looks sharper than healed work — this is the healed kind.",
  "note": "Every case starts from a different point. What is realistic for you is decided from a daylight photo of your own, not from someone else's result.",
  "gallery": [
    {"img": "gallery-brows-01.webp", "alt": "Healed powder brows, close-up", "tag": "Powder brows",
     "caption": "Soft powder finish, denser at the tail than at the front."},
    {"img": "gallery-lips-01.webp", "alt": "Healed lip blush in a deep berry tone", "tag": "Lip blush",
     "caption": "Deep berry, worked into the lip with no lipstick edge."},
    {"img": "gallery-face-01.webp", "alt": "Client with healed powder brows and lip blush", "tag": "Brows + lips",
     "caption": "Brows and lips in one plan, matched to the same undertone."},
    {"img": "gallery-lips-02.webp", "alt": "Healed lip blush in a warm red tone", "tag": "Lip blush",
     "caption": "Warm red on a neutral undertone, border restored."},
    {"img": "gallery-face-02.webp", "alt": "Client with healed powder brows and lip blush", "tag": "Brows + lips",
     "caption": "Shape mapped to the face rather than to a template."},
    {"img": "gallery-face-03.webp", "alt": "Client with healed powder brows and lip blush", "tag": "Brows + lips",
     "caption": "Muted rose lip against a cool undertone."},
  ],
  "cta": {"eyebrow": "Your turn", "h2": "See what is realistic for you",
          "lead": "Send a daylight photo and you get an honest read before anything is booked.",
          "primary": "Message on WhatsApp", "secondary": "Contact details"},
},
"about": {
  "eyebrow": "About",
  "h1": "Milana — PMU artist in the UAE",
  "lead": "Russian permanent makeup and camouflage artist, working at clients' homes across Dubai and Sharjah.",
  "img_alt": "Placeholder for a portrait of Milana at work",
  "paras": [
    "I work with four things: brows, lips, lashline and camouflage. That is deliberate. Camouflage in particular is slow, technical work — matching a pigment to skin, watching how it heals, correcting on the next session — and it does not sit comfortably alongside a menu of twenty treatments.",
    "Every appointment starts with your skin rather than with a pigment chart. Undertone is read in daylight, the mix is made on the day, and it is tested on you before the first pass. On camouflage it is tested and left to heal before a full area is started.",
    "And I come to you. Home service is not a compromise here: it means you heal in your own space, without a drive across the city in the sun on day one.",
  ],
  "founder_label": "Founder:",
  "principles_eyebrow": "How I work",
  "principles_h2": "Three rules I don't break",
  "principles": [
    {"title": "Shape before pigment",
     "text": "Nothing is tattooed until you have seen the drawn shape in a mirror and agreed to it. If we cannot agree on the shape, we do not start — and you pay nothing."},
    {"title": "Lighter than the target",
     "text": "Pigment darkens as it heals, so the first session builds a base deliberately under the final colour. The touch-up is where the colour is set. Anyone who finishes in one pass is guessing."},
    {"title": "Honest about what is possible",
     "text": "Some scars should not be tattooed, and some brows need a correction before anything new goes in. You get that answer before you pay a deposit, not after."},
  ],
  "standards_eyebrow": "Safety",
  "standards_h2": "Sterile, single-use, opened in front of you",
  "standards_lead": "A home service does not mean relaxed standards. The setup that arrives at your door is the setup you would expect to see in a studio.",
  "standards": [
    "Needles and cartridges are single-use and unsealed in front of you",
    "Pigment cups, gloves, razors and liners are disposable",
    "Barrier film on every surface and on the machine",
    "Medical history and contraindications checked before the date is confirmed",
    "A patch test before any camouflage area is started",
    "Written aftercare, and a check-in during the healing week",
  ],
  "standards_img_alt": "Placeholder for a photograph of the sterile setup",
  "cta": {"eyebrow": "Booking", "h2": "Ask me anything first",
          "lead": "Most people message before they book. Questions about a scar, an old brow tattoo or a medication cost nothing to ask.",
          "primary": "Message on WhatsApp", "secondary": "Contact details"},
},

"faq": {
  "eyebrow": "FAQ",
  "h1": "Questions before booking",
  "lead": "The ones that come up in DMs every week. If yours is not here, send it — an honest answer costs nothing.",
  "medical_note": "This page is general information about the treatments, not medical advice. If you have a medical condition, take regular medication, or are unsure about a scar, ask your doctor before booking.",
  "groups": [
    {"title": "Before the appointment", "items": [
      {"q": "Does it hurt?", "a": [
        "Topical anaesthetic goes on before and during the session. Most clients describe brows as scratching and lips as a warm buzzing. Camouflage on the body is usually the easiest of the three.",
        "Skin is more sensitive in the week before a period — worth planning around."]},
      {"q": "Who should not have permanent makeup?", "a": [
        "It is not done during pregnancy or breastfeeding, on active infection or inflammation in the area, or on keloid-prone skin. Ask your doctor first if you have diabetes, an autoimmune condition, take blood thinners, or have used isotretinoin (Accutane) in the last six to twelve months.",
        "Tell me about any of these at the consultation. Several of them mean waiting, not never."]},
      {"q": "What do I need to prepare at home?", "a": [
        "A table or a bed you can lie on, a socket nearby, and a room with daylight if possible. Set aside about three hours without interruptions.",
        "Skip caffeine and alcohol on the day, and keep acids and retinol off the area for a week before."]},
      {"q": "Can you fix work done by someone else?", "a": [
        "Sometimes. Send daylight photos of how it looks now and I will tell you whether it can be worked over, whether it needs lightening first, or whether it is better left to fade."]},
    ]},
    {"title": "During the session", "items": [
      {"q": "How long does it take?", "a": [
        "Two and a half to three hours for brows or lips, including the consultation and the shape mapping. One to three hours for a camouflage area."]},
      {"q": "Do I choose the colour?", "a": [
        "You choose the direction — warmer, cooler, softer, stronger. I mix within what your undertone will actually hold, and I will say so plainly if a request is going to heal badly."]},
      {"q": "Will it look like makeup?", "a": [
        "On day one it looks stronger than the final result. Healed, powder brows read as a light powder and lip blush reads as your lips with more colour in them — not as lipstick."]},
    ]},
    {"title": "Healing and aftercare", "items": [
      {"q": "What does the first month look like?", "a": [
        "Darkest around day two or three, flaking from day four to seven, a patchy grey stage in week two, and true colour around day 28. The full timeline is on the home page."]},
      {"q": "Can I swim, work out or sunbathe?", "a": [
        "No pool, sea or sauna for two weeks, no heavy sweating in the first week, and no direct sun on the area until it has fully healed. After that, SPF is what keeps the colour."]},
      {"q": "Do I have to have the touch-up?", "a": [
        "Yes, if you want the result the photographs show. The first session builds the base; the second sets the colour and corrects anything that healed unevenly. Between four and eight weeks after the first."]},
    ]},
    {"title": "Camouflage", "items": [
      {"q": "How soon after surgery can a scar be treated?", "a": [
        "Usually at least twelve months, and only once your surgeon or doctor confirms the scar is mature, closed and no longer changing. Working too early can affect how it settles."]},
      {"q": "Which scars are not suitable?", "a": [
        "Raised, keloid or hypertrophic scars, anything still red or purple, and scars that are still changing. Skin that tans strongly is also harder to match: the surrounding skin moves with the sun and the pigment does not."]},
      {"q": "Does it work on stretch marks?", "a": [
        "On white, mature stretch marks that have lost their pigment, yes. On red or purple ones, no — they are still changing, and so is their colour."]},
      {"q": "How many sessions does an area take?", "a": [
        "Usually two to four, eight to twelve weeks apart. The gap is not padding: scar tissue holds pigment unpredictably, and each session is planned from how the last one healed."]},
      {"q": "Will the scar disappear completely?", "a": [
        "No — and anyone who promises that is selling something. Camouflage removes the colour contrast, not the texture. In daylight, at conversational distance, a well-matched area stops drawing the eye. That is the honest goal."]},
    ]},
  ],
  "cta": {"eyebrow": "Still unsure", "h2": "Ask the question directly",
          "lead": "If your situation is not covered here, message me. I would rather talk you out of a treatment than do one that will not work.",
          "primary": "Message on WhatsApp", "secondary": "Contact details"},
},

"contact": {
  "eyebrow": "Contact",
  "h1": "Book a session",
  "lead": "WhatsApp is the fastest way to reach me. Send a photo of the area and you will know what is realistic before you commit to anything.",
  "direct_h2": "Message directly",
  "direct_lead": "Answers usually within a few hours. Daylight photos, please — indoor lighting hides undertone completely.",
  "wa_cta": "Open WhatsApp",
  "channels": [
    {"icon": "whatsapp", "label": "WhatsApp", "value": "__PHONE__", "href": "__WA__"},
    {"icon": "phone", "label": "Phone", "value": "__PHONE__", "href": "__TEL__"},
    {"icon": "mail", "label": "Email", "value": "__EMAIL__", "href": "__MAILTO__"},
    {"icon": "instagram", "label": "Instagram", "value": "__IG_HANDLE__", "href": "__IG__"},
    {"icon": "pin", "label": "Service area", "value": "Dubai & Sharjah — home visits", "href": "#areas"},
  ],
  "form": {
    "h2": "Or send the details",
    "lead": "This fills in a WhatsApp message for you. Nothing is stored on this site.",
    "name": "Your name", "phone": "Phone number", "service": "Treatment",
    "area": "Where you are", "area_ph": "e.g. Jumeirah, Dubai",
    "message": "Anything I should know",
    "message_ph": "Age of the scar, previous PMU, medication, dates that suit you",
    "message_hint": "For camouflage, attach a daylight photo in the WhatsApp chat that opens.",
    "submit": "Open WhatsApp with this",
    "note": "The button opens WhatsApp with your details filled in. Nothing is sent until you press send there.",
    "services": ["Powder brows", "Lip blush", "Lashline", "Powder brows + lip blush",
                 "Scar camouflage", "Stretch mark camouflage",
                 "Scalp camouflage", "Correction of previous PMU", "Not sure yet"],
  },
  "areas_eyebrow": "Coverage",
  "areas_h2": "Where I work",
  "areas_lead": "Home visits across Dubai and Sharjah, with travel included in the price.",
  "areas_items": [
    ("Dubai", "Marina, JLT, Downtown, Business Bay, Jumeirah, Al Barsha, JVC, Mirdif and the rest of the city."),
    ("Sharjah", "Al Majaz, Al Nahda, Al Khan, Muwaileh and the surrounding areas."),
    ("Further out", "Ajman and Abu Dhabi by arrangement — message me with your location and the dates that suit you."),
  ],
  "cta": {"eyebrow": "Booking", "h2": "Message me today",
          "lead": "Tell me what you want changed and send a daylight photo. You get a straight answer, a price and a realistic timeline.",
          "primary": "Message on WhatsApp", "secondary": "Contact details"},
},

"book": {
  "h2": "Book a session",
  "lead": "Pick whichever suits you. Send a daylight photo of the area and you get an honest read before anything is booked.",
  "close": "Close",
  "note": "For camouflage, include the age of the scar and a photo taken in daylight — indoor lighting hides undertone completely.",
  "options": [
    {"icon": "whatsapp", "title": "WhatsApp", "desc": "Fastest — usually a reply within a few hours"},
    {"icon": "instagram", "title": "Instagram DM", "desc": "__IG_HANDLE__ — recent work and healed results"},
    {"icon": "phone", "title": "Call", "desc": "__PHONE__"},
    {"icon": "form", "title": "Booking form", "desc": "Send your details in one go"},
  ],
},
}
